#+title:Arsalan Kazmi - Terms I use
#+options: toc:nil html-postamble:nil num:nil title:nil html-style:nil
#+html_head: <link rel="shortcut icon" href="https://avatars.githubusercontent.com/u/16748384" type="image/png">
#+html_head: <link rel="stylesheet" href="m8.css" type="text/css">
#+begin_export html
<a href="index.html"><img src="https://avatars.githubusercontent.com/u/16748384" class="avatar"></img></a>
#+end_export
* Arsalan Kazmi
  :PROPERTIES:
  :CUSTOM_ID: arsalan-kazmi
  :END:
#+begin_export html
<p id="comment">/* 20 year old college student who likes doing stupid stuff with computers */</p>
#+end_export

[[file:thestuffindex.html][Return to The Stuff Index]]

** Terms I use
There are certain technical-ish terms that I use. Here's a list of them.
*** Free software
Free software means software that is free to use. Not software that you get /for/ free, but software that comes with no restrictions on usage, copying, redistribution or modification. It's synonymous with "open source software".
*** FLOSS
FLOSS is an acronym that stands for "free (libre) and open source software". The "free" in the acronym means "free to use" as explained above.
*** GNU/Linux
I only use the name "GNU/Linux" to refer to Linux-based OSes that use the GNU system. I don't use it for distributions unless the distro maintainers do, i.e. I don't call Arch Linux "Arch GNU/Linux", but I do call Debian "Debian GNU/Linux".
*** Victory key
The Victory key is the Super/Windows key. I call it "Victory" because "Windows key" can be shortened to "Win key" and "Win" became "Victory".

#+begin_export html
<br>
<p id="comment">/* Click the avatar to return back to the index */</p>
#+end_export
